### ISSUE TITLE
Create required Jenkinsfile for synching the website with the github repo.

### ISSUE THREAD

**Issue by niraj-modi** [eclipse-platform/www.eclipse.org-swt#1]
For reference see:
https://wiki.eclipse.org/Jenkins#How_to_build_my_project.27s_website_with_Jenkins.3F

**Comment by laeubi** [comment]
I'd like to remind about some effort @wimjongman already did to use https://docs.github.com/en/pages maybe that would allow a more smooth workflow?

**Comment by wimjongman** [comment]
Yes, I converted the old platform website from PHP to Hugo. Unfortunately, the effort was blocked by @mickaelistria. It can be picked up again with minor effort. The details are in this thread [2]

[1] https://testuser:plaintext@staging.eclipse.org/eclipse/
[2] https://www.eclipse.org/lists/platform-dev/msg02819.html
