### ISSUE TITLE
Update Snippets page to point to SWT Snippets.md file

### ISSUE THREAD

**Issue by Phillipus** [eclipse-platform/www.eclipse.org-swt#7]
I've created a markdown file with the list of Snippets:

https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/examples/org.eclipse.swt.snippets/Snippets.md

The snippets web page [here:](https://github.com/eclipse-platform/www.eclipse.org-swt/blob/master/snippets/index.php) should be updated to point to the new `Snippets.md` file

See:

https://github.com/eclipse-platform/eclipse.platform.swt/issues/334#issuecomment-1224287253

I would normally submit a PR but there is some PHP in index.php and I couldn't test any changes and didn't want to mess it up.

**Comment by vogella** [comment]
I think this is solved. @Phillipus if not please re-open
